#! /bin/sh
#
# this script is provided under GPL v3 or upper


COLUMNS=`tput cols`
MARGINS=10
RULE_LENGTH=`echo ${COLUMNS}-${MARGINS} | bc`

printf "\n     "


for i in $(seq 1 $RULE_LENGTH);
do
    printf "━"
done

echo "\n"

