#! /bin/sh
#
# this script is provided under GPL v3 or upper


COLUMNS=`tput cols`
MARGIN_LEFT=5
MARGINS=`echo ${MARGIN_LEFT}*2 | bc`
RULE_LENGTH=`echo ${COLUMNS}-${MARGINS} | bc`
SPACE_HEIGHT="true"

if [ "$#" -gt 0 ] ; then
    if [ "$1" = "-c" ] || [ "$1" = "--compact" ] ; then
        SPACE_HEIGHT=""
    fi
fi


if [ ${SPACE_HEIGHT} ]; then
    printf "\n"
fi

for i in $(seq 1 ${MARGIN_LEFT});
do
    printf " "
done

for i in $(seq 1 ${RULE_LENGTH});
do
    printf "━"
done

if [ ${SPACE_HEIGHT} ]; then
    printf "\n"
fi

printf "\n"

