#! /bin/sh
#
# this script is provided under GPL v3 or upper


COLUMNS=`tput cols`
MARGIN_LEFT=5
MARGINS=`echo ${MARGIN_LEFT}*2 | bc`
RULE_LENGTH=`echo ${COLUMNS}-${MARGINS} | bc`

printf "\n"

for i in $(seq 1 ${MARGIN_LEFT});
do
    printf " "
done

for i in $(seq 1 ${RULE_LENGTH});
do
    printf "━"
done

echo "\n"

