.TH HR 1 "February 21, 2016"
.SH NAME
hr \- Draw an horizontal rule to stdout.
.SH SYNOPSIS
.B hr
.RI [ -c|--compact ]
.SH DESCRIPTION
Draw an horizontal rule to stdout. The width of the separator depends of the
width of the terminal.
.SH OPTIONS
.TP
.B \-c, \-\-compact
No empty line before and after the separator
.SH AUTHOR
hr was written by Stephane Blondon.
This manual page was written by the author and is released under the same licence of the `hr` script.
